# dryRun true is parse only, not load database and not delete/move files
dryRun: true
# problem files
failureDir: /Users/gsc/Documents/github/mellow-heeler/failures
# raw files to process
importDir: /Users/gsc/Documents/github/mellow-heeler/samples
#
dbConn: "postgresql+psycopg2://heeler_py:bogus@localhost:5432/heeler_v1"
#
# kill below
#
#
#gzipCommand: /bin/gzip
gzipCommand: /usr/bin/gzip
#
dbUserName: seagull
dbPassWord: bogus
dbDataBase: vocal_seagull
dbHostName: localhost
#
