#
#exportDir: /Users/gsc/Documents/github/mellow-heeler/aws_export
#exportDir: /home/gsc/github/mellow-heeler/aws_export
#exportDir: /home/gsc/github/mellow-heeler/aws_export
exportDir: /home/gsc/Documents/github/mellow-heeler/aws-export
#
#AWS_ACCESS_KEY_ID: bogus
#AWS_SECRET_ACCESS_KEY: bogus
#AWS_DEFAULT_REGION: us-west-2
#
#gzipCommand: /bin/gzip
gzipCommand: /usr/bin/gzip
#
dbUserName: seagull
dbPassWord: bogus
dbDataBase: vocal_seagull
dbHostName: localhost
#
