--
-- Title: observation.psql
-- Description: WAP observation
--
-- level = signal strength
-- 
create table observation (
  id          bigserial    primary key,
  geoloc_id   bigint       not null,
  constraint  geoloc_id    foreign key(geoloc_id) references geoloc(id),
  level       smallint     not null,
  time_stamp  timestamptz  not null default CURRENT_TIMESTAMP,
  wap_id      bigint       not null,
  constraint  wap_id       foreign key(wap_id) references wap(id)
); 
